version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: mail-10-minutes-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_DATABASE: mail_10_minutes
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: '1'
      user: 'user'
      LANG: C.UTF-8
    user: 'root'  
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3100:3306
