from fastapi import APIRouter
import random
import string
from datetime import datetime
import requests

#mail
import smtplib
from socket import gaierror

#config mailtrap
port = 587
smtp_server = "smtp.mailtrap.io"
login = "85f90b564d608c" # paste your login generated by Mailtrap
password = "ee1707abd68686" # paste your password generated by Mailtrap

import sys
sys.path.insert(0,'/home/chihieu/project_web/test_poetry/config')
sys.path.insert(1,'/home/chihieu/project_web/test_poetry/models')

from db import conn
from index import email
from index import emailData

emailRouter = APIRouter()


# send email from this email to that email
@emailRouter.post("/send-email")
async def simple_send(sender: str, receiver: str, message: str):
  content = f"""\
        Subject: Hi Mailtrap
        To: {receiver}
        From: {sender}
        {message}."""

  try:
    #send your message with credentials specified above
    with smtplib.SMTP(smtp_server, port) as server:
        server.login(login, password)
        print("login successful")
        server.sendmail(sender, receiver, content)
        user = conn.execute(email.select().where(email.c.name == receiver)).fetchone()
        print('Sent')
        return conn.execute(emailData.insert().values(
          receiver_id=user.id,
          sender=sender,
          content=message,
        ))
        
    # tell the script to report if your message was sent or which errors need to be fixed 
   
  except (gaierror, ConnectionRefusedError):
    print('Failed to connect to the server. Bad connection settings?')
  except smtplib.SMTPServerDisconnected:
    print('Failed to connect to the server. Wrong user/password?')
  except smtplib.SMTPException as e:
    print('SMTP error occurred: ' + str(e))


# get all email in system
@emailRouter.get("/")
async def read_data():
  return conn.execute(email.select()).fetchall()


# get inbox of email
@emailRouter.get("/inbox")
async def get_inbox(name: str):
  user = conn.execute(email.select().where(email.c.name == name)).fetchone()
  result = datetime.utcnow().timestamp() - user.created_at.timestamp()
  print(result)
  
  
  if(user and result <= 10*60):
    inbox = conn.execute(emailData.select().where(emailData.c.receiver_id == user.id)).fetchall()
    return inbox

# random email func
def random_char(char_num):
       return ''.join(random.choice(string.ascii_letters) for _ in range(char_num))

# random email and save to database
@emailRouter.post("/")
async def random_email_func():
    email_rand = random_char(8)+"@gmail.com"
    data = conn.execute(email.insert().values(
      name=email_rand
    ))
    return data.is_insert


